import "server-only"
import type { AIToolDefinition } from "@/lib/ai/tools/context"
import { getAdminUserActivityLogTool } from "@/lib/ai/tools/get-admin-user-activity-log"
import { getAdminUserProfileOverviewTool } from "@/lib/ai/tools/get-admin-user-profile-overview"
import { getAdminUserSessionsTool } from "@/lib/ai/tools/get-admin-user-sessions"
import { getMyActivityLogTool } from "@/lib/ai/tools/get-my-activity-log"
import { getMyChatSummaryTool } from "@/lib/ai/tools/get-my-chat-summary"
import { getMyChatThreadMessagesTool } from "@/lib/ai/tools/get-my-chat-thread-messages"
import { getMyChatThreadsOverviewTool } from "@/lib/ai/tools/get-my-chat-threads-overview"
import { getMyFriendsDetailTool } from "@/lib/ai/tools/get-my-friends-detail"
import { getMyFriendsOverviewTool } from "@/lib/ai/tools/get-my-friends-overview"
import { getMyInterviewsOverviewTool } from "@/lib/ai/tools/get-my-interviews-overview"
import { getMyJobsOverviewTool } from "@/lib/ai/tools/get-my-jobs-overview"
import { getMyPostsOverviewTool } from "@/lib/ai/tools/get-my-posts-overview"
import { getMyProfileTool } from "@/lib/ai/tools/get-my-profile"
import { getMyResumeOverviewTool } from "@/lib/ai/tools/get-my-resume-overview"
import { getMySessionsOverviewTool } from "@/lib/ai/tools/get-my-sessions-overview"
import { getMySettingsTool } from "@/lib/ai/tools/get-my-settings"
import { getMyUploadsOverviewTool } from "@/lib/ai/tools/get-my-uploads-overview"
import { searchMyChatMessagesTool } from "@/lib/ai/tools/search-my-chat-messages"
import {
  getMyPermissionsTool,
  getMyModuleVisibilityTool,
  getMyHomeOverviewTool,
  getMyResumeDetailTool,
  getMyResumeVersionsTool,
  listMyPostsTool,
  searchMyPostsTool,
  getMyPostDetailTool,
  getMyPostContentTool,
  listMyJobsTool,
  getMyJobDetailTool,
  listMyInterviewsTool,
  getMyInterviewDetailTool,
  listMyFriendsTool,
  getMyFriendProfileTool,
} from "@/lib/ai/tools/self-read-tools"
import {
  getVisibleUserPermissionsTool,
  getVisibleUserHomeOverviewTool,
  getVisibleUserResumeDetailTool,
  listVisibleUserPostsTool,
  getVisibleUserPostContentTool,
  listVisibleUserJobsTool,
  getVisibleUserJobDetailTool,
  listVisibleUserInterviewsTool,
  getVisibleUserInterviewDetailTool,
} from "@/lib/ai/tools/visible-user-tools"
import {
  getAdminSelfPermissionsTool,
  listAdminUsersTool,
  getAdminUserDetailTool,
  listAdminUserSessionsTool,
  listAdminUserActivityLogsTool,
  listAdminAIAccessRequestsTool,
  listAdminAIGrantsTool,
  listAdminAIAuditLogsTool,
  getAdminOverviewTool,
} from "@/lib/ai/tools/admin-read-tools"
import { getVisibleUserPageOverviewTool } from "@/lib/ai/tools/get-visible-user-page-overview"
import {
  createMarkdownArticleTool,
  updateMarkdownArticleTool,
  getMarkdownArticleDetailTool,
  listMarkdownArticlesTool,
  createContentFolderTool,
  listContentFoldersTool,
  moveArticleToFolderTool,
} from "@/lib/ai/tools/markdown-content-tools"
import {
  saveUserMemoryTool,
  searchUserMemoryTool,
  listUserMemoriesTool,
  forgetUserMemoryTool,
} from "@/lib/ai/tools/memory-tools"
import { updateAgentProfileTool } from "@/lib/ai/tools/agent-profile-tools"
import { listMyCapabilitiesTool, searchMyCapabilitiesTool } from "@/lib/ai/tools/capability-tools"
import { proposeSaveUserContextTool } from "@/lib/ai/tools/propose-user-context-tool"
import { getAutoReplySettingsTool, updateAutoReplySettingsTool } from "@/lib/ai/tools/auto-reply-tools"
import { listMyChannelsTool, getChannelMessagesTool } from "@/lib/ai/tools/channel-tools"
import { getSoulWingRoundtableRecordsTool } from "@/lib/ai/tools/soulwing-roundtable-tools"
import { sendDraftChatMessageTool } from "@/lib/ai/tools/chat-draft-tools"
import { summarizeChatThreadTool } from "@/lib/ai/tools/summarize-thread-tool"
import { deleteMyMemoryFactBatchTool } from "@/lib/ai/tools/memory-batch-tools"
import { setModuleVisibilityTool } from "@/lib/ai/tools/module-visibility-tools"
import { searchSoulWingConversationsTool } from "@/lib/ai/tools/search-soulwing-conversations"
import { webSearchTool, webVerifyCurrentInfoTool } from "@/lib/ai/tools/web-search-tools"
import type { AIToolDescriptor } from "@/lib/ai/types"

function defineTool<TInput extends Record<string, unknown> | void>(
  tool: {
    name: string
    title: string
    description: string
    execute: AIToolDefinition<TInput>["execute"]
  },
  meta: Omit<AIToolDescriptor, "name" | "title" | "description">
): AIToolDefinition<TInput> {
  return {
    ...tool,
    ...meta,
  }
}

const selfSummary = "适合当前用户读取自己的资料、内容与站内记录。"

export const AI_TOOLS_REGISTRY = [
  defineTool(getMyProfileTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "low",
    auditLabel: "read_self_profile",
    whenToUse: `${selfSummary} 查询我的基础资料、昵称、邮箱、简介时使用。`,
    whenNotToUse: "不要用于读取管理员后台数据、好友可见内容或文章全文。",
    argumentHints: [],
    returns: "用户基础资料。",
  }),
  defineTool(getMyPermissionsTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_permissions",
    whenToUse: "当问题是“我是不是管理员”“我有哪些权限”“我的模块对好友怎么开放”时使用。",
    whenNotToUse: "不要用于读取具体文章、岗位或聊天内容。",
    argumentHints: [],
    returns: "用户角色、管理员权限和模块开放设置。",
  }),
  defineTool(getMyModuleVisibilityTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_module_visibility",
    whenToUse: "当问题只关心主页模块开放状态时使用。",
    whenNotToUse: "不要用于读取具体模块内容。",
    argumentHints: [],
    returns: "各模块 visibility。",
  }),
  defineTool(getMySettingsTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "low",
    auditLabel: "read_self_settings",
    whenToUse: "当问题关心站点设置、语言、ownerName、heroTagline 等配置时使用。",
    whenNotToUse: "不要用于读取主页聚合内容、权限或文章正文。",
    argumentHints: [],
    returns: "站点设置。",
  }),
  defineTool(getMyHomeOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_home_overview",
    whenToUse: "当用户想了解主页都有哪些模块、主页现在有哪些内容、主页概况如何时使用。",
    whenNotToUse: "不要用于替代简历全文、文章全文或单条求职/面试详情。",
    argumentHints: [],
    returns: "主页设置、布局和各模块数据计数。",
  }),
  defineTool(getMyResumeOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_resume_overview",
    whenToUse: "当只需要简历概况、模式和版本数量时使用。",
    whenNotToUse: "如果需要简历完整内容，改用 get_my_resume_detail。",
    argumentHints: [],
    returns: "简历模式、是否有 PDF、字数和版本数。",
  }),
  defineTool(getMyResumeDetailTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "high",
    auditLabel: "read_self_resume_detail",
    whenToUse: "当用户明确要看简历全文、帮忙润色简历、总结简历内容时使用。",
    whenNotToUse: "不要只为了回答概况问题就读取全文。",
    argumentHints: [],
    returns: "简历完整内容和模式。",
  }),
  defineTool(getMyResumeVersionsTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_resume_versions",
    whenToUse: "当用户想知道简历有哪些 PDF 版本时使用。",
    whenNotToUse: "不要用于读取简历正文。",
    argumentHints: [],
    returns: "简历版本列表。",
  }),
  defineTool(getMyPostsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "low",
    auditLabel: "read_self_posts_overview",
    whenToUse: "当只需要文章总量、类型分布和最近文章概况时使用。",
    whenNotToUse: "如果用户要找具体文章或读全文，优先用 list/search/detail/content 工具。",
    argumentHints: [],
    returns: "文章概览。",
  }),
  defineTool(listMyPostsTool, {
    scope: "self",
    inputSchemaSummary: "postType?: string, limit?: number, query?: string",
    sensitivity: "medium",
    auditLabel: "list_self_posts",
    whenToUse: "当用户要查看博客、日常、心得、笔记列表，或先找某篇文章时使用。",
    whenNotToUse: "不要默认读取全文。",
    argumentHints: ["postType 可选值：blog/daily/reflections/notes", "query 可按标题、摘要、标签过滤"],
    returns: "文章列表。",
  }),
  defineTool(searchMyPostsTool, {
    scope: "self",
    inputSchemaSummary: "query: string, postType?: string, limit?: number",
    sensitivity: "high",
    auditLabel: "search_self_posts",
    whenToUse: "当用户要按关键词搜索文章时使用。触发语：'找找有没有关于……的文章''搜索我的笔记''找到那篇关于……的博客'。",
    whenNotToUse: "如果已知具体 slug 或 postId，直接用详情或全文工具。",
    argumentHints: ["query 必填", "会搜索标题、摘要、标签和正文"],
    returns: "匹配文章及内容片段。",
  }),
  defineTool(getMyPostDetailTool, {
    scope: "self",
    inputSchemaSummary: "postId?: string, slug?: string, postType?: string",
    sensitivity: "medium",
    auditLabel: "read_self_post_detail",
    whenToUse: "当用户想知道某篇文章的标题、摘要、标签等详情时使用。",
    whenNotToUse: "如果明确要求全文，改用 get_my_post_content。",
    argumentHints: ["优先传 postId；否则传 slug + postType"],
    returns: "文章详情，不含正文。",
  }),
  defineTool(getMyPostContentTool, {
    scope: "self",
    inputSchemaSummary: "postId?: string, slug?: string, postType?: string",
    sensitivity: "high",
    auditLabel: "read_self_post_content",
    whenToUse: "当用户明确要求读取某篇文章全文或基于全文总结时使用。",
    whenNotToUse: "不要为纯概况问题读取全文。",
    argumentHints: ["优先传 postId；否则传 slug + postType"],
    returns: "文章全文。",
  }),
  defineTool(getMyJobsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_jobs_overview",
    whenToUse: "当用户只想知道求职整体进展、回复率、面试率时使用。",
    whenNotToUse: "如果要单条记录详情，改用 list/get detail。",
    argumentHints: [],
    returns: "求职统计概览。",
  }),
  defineTool(listMyJobsTool, {
    scope: "self",
    inputSchemaSummary: "status?: string, query?: string, limit?: number",
    sensitivity: "medium",
    auditLabel: "list_self_jobs",
    whenToUse: "当用户想看最近投了哪些岗位、某类状态岗位列表时使用。",
    whenNotToUse: "不要替代单条详情工具。",
    argumentHints: ["可按 status 或 query 过滤"],
    returns: "求职记录列表。",
  }),
  defineTool(getMyJobDetailTool, {
    scope: "self",
    inputSchemaSummary: "jobId: string",
    sensitivity: "high",
    auditLabel: "read_self_job_detail",
    whenToUse: "当用户要查看某条求职记录的完整字段时使用。",
    whenNotToUse: "不要在只问整体趋势时调用。",
    argumentHints: ["jobId 必填"],
    returns: "单条求职详情。",
  }),
  defineTool(getMyInterviewsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_interviews_overview",
    whenToUse: "当用户只关心面试整体情况、通过率、分布时使用。",
    whenNotToUse: "如果要看单条面试复盘，改用 list/detail。",
    argumentHints: [],
    returns: "面试概览。",
  }),
  defineTool(listMyInterviewsTool, {
    scope: "self",
    inputSchemaSummary: "result?: string, query?: string, limit?: number",
    sensitivity: "medium",
    auditLabel: "list_self_interviews",
    whenToUse: "当用户想看最近面试、某家公司面试、某种结果的面试列表时使用。",
    whenNotToUse: "不要替代单条详情工具。",
    argumentHints: ["可按 result 或 query 过滤"],
    returns: "面试记录列表。",
  }),
  defineTool(getMyInterviewDetailTool, {
    scope: "self",
    inputSchemaSummary: "interviewId: string",
    sensitivity: "high",
    auditLabel: "read_self_interview_detail",
    whenToUse: "当用户要查看某次面试的题目、反馈、自评等完整信息时使用。",
    whenNotToUse: "不要在只问整体趋势时调用。",
    argumentHints: ["interviewId 必填"],
    returns: "单条面试详情。",
  }),
  defineTool(getMyUploadsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_uploads",
    whenToUse: "当用户要看最近上传记录时使用。",
    whenNotToUse: "不要用于图片理解或文章/简历内容读取。",
    argumentHints: [],
    returns: "上传概览。",
  }),
  defineTool(getMyFriendsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_friends_overview",
    whenToUse: "当只需要好友数量和互动态势概况时使用。",
    whenNotToUse: "如果要具体好友资料，优先用 list_my_friends 或 get_my_friend_profile。",
    argumentHints: [],
    returns: "好友概览。",
  }),
  defineTool(getMyFriendsDetailTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_self_friends_detail",
    whenToUse: "当需要好友列表与最近互动明细时使用。",
    whenNotToUse: "不要用于读取单个好友的完整资料。",
    argumentHints: [],
    returns: "好友明细。",
  }),
  defineTool(listMyFriendsTool, {
    scope: "self",
    inputSchemaSummary: "limit?: number",
    sensitivity: "medium",
    auditLabel: "list_self_friends",
    whenToUse: "当用户要查看好友资料列表时使用。",
    whenNotToUse: "不要用于读取聊天消息。",
    argumentHints: ["默认返回最近加入的好友"],
    returns: "好友列表及资料摘要。",
  }),
  defineTool(getMyFriendProfileTool, {
    scope: "self",
    inputSchemaSummary: "friendId?: string, friendHint?: string",
    sensitivity: "medium",
    auditLabel: "read_self_friend_profile",
    whenToUse: "当用户想看某位好友的昵称、邮箱、个签、地区、最近互动时使用。",
    whenNotToUse: "不要用于读取整个好友列表。",
    argumentHints: ["friendHint 可传昵称、邮箱或用户 id 片段"],
    returns: "单个好友资料。",
  }),
  defineTool(getMyChatSummaryTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "high",
    auditLabel: "read_self_chat_summary",
    whenToUse: "当用户问聊天总体趋势、总消息数、最活跃对象时使用。",
    whenNotToUse: "不要替代线程列表或线程消息工具。",
    argumentHints: [],
    returns: "聊天整体概况。",
  }),
  defineTool(getMyChatThreadsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "high",
    auditLabel: "read_self_chat_threads",
    whenToUse: "当用户想知道最近和哪个好友聊得最多、好友聊天线程排行时使用。",
    whenNotToUse: "不要用于搜索具体消息内容。重要：本工具返回的是用户与好友的聊天排行，不是 AI 对话统计。当用户问【我跟你聊了几次】默认指与蝶灵的对话次数，应使用 search_soulwing_conversations (mode=count)。",
    argumentHints: [],
    returns: "聊天线程排行。",
  }),
  defineTool(searchMyChatMessagesTool, {
    scope: "self",
    inputSchemaSummary: "query?: string, peerHint?: string, limit?: number",
    sensitivity: "high",
    auditLabel: "search_self_chat_messages",
    whenToUse: "当用户要在好友聊天记录里按关键词搜索消息时使用。触发语：'搜索聊天记录''找找和……聊的消息''聊天记录里有没有关于……的内容'。",
    whenNotToUse: "不要在没有搜索需求时调用。重要：本工具查询的是用户与好友的私聊消息（ChatMessage），不是用户与蝶灵 SoulWing 的 AI 对话。当用户说【我跟你聊了】默认指与 AI 助手的对话，应使用 search_soulwing_conversations。",
    argumentHints: ["query 为关键词", "peerHint 可传对象昵称、邮箱或 id 片段"],
    returns: "聊天消息搜索结果。",
  }),
  defineTool(getMyChatThreadMessagesTool, {
    scope: "self",
    inputSchemaSummary: "peerHint?: string, limit?: number",
    sensitivity: "high",
    auditLabel: "read_self_chat_thread",
    whenToUse: "当用户要看和某个好友的聊天内容时使用。",
    whenNotToUse: "不要用于线程排行或搜索全局聊天。重要：本工具查询的是用户与某个好友的私聊消息，不是用户与蝶灵 SoulWing 的 AI 对话。当用户说【我和你的聊天记录】默认指 AI 对话历史，应使用 search_soulwing_conversations (mode=messages)。",
    argumentHints: ["peerHint 建议传好友昵称、邮箱或 id 片段"],
    returns: "单个聊天线程消息。",
  }),
  defineTool(getMySessionsOverviewTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "high",
    auditLabel: "read_self_sessions",
    whenToUse: "当用户想看自己的登录设备、IP、会话安全信息时使用。",
    whenNotToUse: "不要用于管理员代查其他用户。重要：本工具返回的是登录设备和会话安全信息，不是 AI 对话记录。当用户问【我跟你聊了几次】时不要使用本工具。",
    argumentHints: [],
    returns: "当前用户会话概览。",
  }),
  defineTool(getMyActivityLogTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "high",
    auditLabel: "read_self_activity_log",
    whenToUse: "当用户想看自己的系统操作日志、登录登出记录时使用。",
    whenNotToUse: "不要用于管理员代查其他用户。重要：本工具返回的是系统登录/登出/操作日志（UserActivity），不是 AI 对话记录。当用户说【我跟你聊了几次】【我最近做了什么】而上下文是与 AI 助手对话时，应使用 search_soulwing_conversations，不是本工具。只有当问题明确指【登录记录】【操作日志】【访问了哪些页面】时才用本工具。",
    argumentHints: [],
    returns: "当前用户活动日志。",
  }),
  defineTool(getVisibleUserPermissionsTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "medium",
    auditLabel: "read_visible_user_permissions",
    whenToUse: "当用户问“我能不能看某好友的博客/简历/主页”时使用。",
    whenNotToUse: "不要用于读取具体内容。",
    argumentHints: ["targetUserId 必填"],
    returns: "目标用户主页模块访问权限。",
  }),
  defineTool(getVisibleUserPageOverviewTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "low",
    auditLabel: "read_visible_user_page_overview",
    whenToUse: "兼容旧的好友页面概览查询。",
    whenNotToUse: "新逻辑优先使用 get_visible_user_permissions 或 get_visible_user_home_overview。",
    argumentHints: ["targetUserId 必填"],
    returns: "旧版可见页面概览。",
    deprecated: true,
  }),
  defineTool(getVisibleUserHomeOverviewTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "medium",
    auditLabel: "read_visible_user_home_overview",
    whenToUse: "当用户想看好友主页都有哪些可见内容时使用。",
    whenNotToUse: "不要替代具体文章、求职、面试详情读取。",
    argumentHints: ["targetUserId 必填"],
    returns: "好友主页可见概览。",
  }),
  defineTool(getVisibleUserResumeDetailTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "high",
    auditLabel: "read_visible_user_resume_detail",
    whenToUse: "当用户有权限且想看好友简历全文时使用。",
    whenNotToUse: "没有权限时不要继续尝试其他私有工具。",
    argumentHints: ["targetUserId 必填"],
    returns: "好友简历全文或拒绝原因。",
  }),
  defineTool(listVisibleUserPostsTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string, postType?: string, query?: string, limit?: number",
    sensitivity: "medium",
    auditLabel: "list_visible_user_posts",
    whenToUse: "当用户想列出某好友的博客、日常、心得或笔记时使用。",
    whenNotToUse: "不要默认读取全文。",
    argumentHints: ["postType 可选值：blog/daily/reflections/notes"],
    returns: "当前用户可见的好友文章列表。",
  }),
  defineTool(getVisibleUserPostContentTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string, postId?: string, slug?: string, postType?: string",
    sensitivity: "high",
    auditLabel: "read_visible_user_post_content",
    whenToUse: "当用户明确需要读取某篇好友文章全文时使用。",
    whenNotToUse: "没有模块权限或文章可见性时不要继续读取。",
    argumentHints: ["优先传 postId；否则传 slug + postType"],
    returns: "好友文章全文或拒绝原因。",
  }),
  defineTool(listVisibleUserJobsTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string, status?: string, query?: string, limit?: number",
    sensitivity: "medium",
    auditLabel: "list_visible_user_jobs",
    whenToUse: "当用户想查看好友求职记录列表时使用。",
    whenNotToUse: "没有 jobs 模块权限时不要调用详情工具。",
    argumentHints: ["targetUserId 必填"],
    returns: "好友求职记录列表。",
  }),
  defineTool(getVisibleUserJobDetailTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string, jobId: string",
    sensitivity: "high",
    auditLabel: "read_visible_user_job_detail",
    whenToUse: "当用户想查看某条好友求职记录详情时使用。",
    whenNotToUse: "没有 jobs 模块权限时不要调用。",
    argumentHints: ["targetUserId 和 jobId 必填"],
    returns: "好友求职详情或拒绝原因。",
  }),
  defineTool(listVisibleUserInterviewsTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string, result?: string, query?: string, limit?: number",
    sensitivity: "medium",
    auditLabel: "list_visible_user_interviews",
    whenToUse: "当用户想查看好友面试记录列表时使用。",
    whenNotToUse: "没有 interviews 模块权限时不要调用详情工具。",
    argumentHints: ["targetUserId 必填"],
    returns: "好友面试记录列表。",
  }),
  defineTool(getVisibleUserInterviewDetailTool, {
    scope: "visible-user",
    inputSchemaSummary: "targetUserId: string, interviewId: string",
    sensitivity: "high",
    auditLabel: "read_visible_user_interview_detail",
    whenToUse: "当用户想查看某条好友面试记录详情时使用。",
    whenNotToUse: "没有 interviews 模块权限时不要调用。",
    argumentHints: ["targetUserId 和 interviewId 必填"],
    returns: "好友面试详情或拒绝原因。",
  }),
  defineTool(getAdminSelfPermissionsTool, {
    scope: "self",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_admin_self_permissions",
    whenToUse: "当当前管理员想确认自己的管理员权限时使用。",
    whenNotToUse: "普通用户问题优先使用 get_my_permissions。",
    argumentHints: [],
    returns: "管理员自身权限。",
  }),
  defineTool(getAdminUserProfileOverviewTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "medium",
    auditLabel: "read_admin_user_profile_overview",
    whenToUse: "兼容旧的后台用户概览查询。",
    whenNotToUse: "新逻辑优先使用 get_admin_user_detail。",
    argumentHints: ["targetUserId 必填"],
    returns: "旧版后台用户概览。",
    deprecated: true,
  }),
  defineTool(listAdminUsersTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "limit?: number, cursor?: string, query?: string",
    sensitivity: "medium",
    auditLabel: "list_admin_users",
    whenToUse: "当管理员想列出后台用户或搜索用户时使用。",
    whenNotToUse: "不要用于单个用户详情。",
    argumentHints: ["支持分页和关键词搜索"],
    returns: "后台用户列表。",
  }),
  defineTool(getAdminUserDetailTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "high",
    auditLabel: "read_admin_user_detail",
    whenToUse: "当管理员要看某位用户资料、权限和 AI 状态时使用。",
    whenNotToUse: "不要用于活动日志或会话列表。",
    argumentHints: ["targetUserId 必填"],
    returns: "后台用户详情。",
  }),
  defineTool(getAdminUserSessionsTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "high",
    auditLabel: "read_admin_user_sessions_overview",
    whenToUse: "兼容旧的后台用户会话概览。",
    whenNotToUse: "需要分页时优先用 list_admin_user_sessions。",
    argumentHints: ["targetUserId 必填"],
    returns: "旧版用户会话概览。",
    deprecated: true,
  }),
  defineTool(listAdminUserSessionsTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "targetUserId: string, limit?: number, cursor?: string",
    sensitivity: "high",
    auditLabel: "list_admin_user_sessions",
    whenToUse: "当管理员要看某位用户的登录会话明细时使用。",
    whenNotToUse: "不要用于读取用户活动日志。",
    argumentHints: ["targetUserId 必填，支持分页"],
    returns: "后台用户会话列表。",
  }),
  defineTool(getAdminUserActivityLogTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "targetUserId: string",
    sensitivity: "high",
    auditLabel: "read_admin_user_activity_log_overview",
    whenToUse: "兼容旧的后台用户活动日志概览。",
    whenNotToUse: "需要分页时优先用 list_admin_user_activity_logs。",
    argumentHints: ["targetUserId 必填"],
    returns: "旧版用户活动日志概览。",
    deprecated: true,
  }),
  defineTool(listAdminUserActivityLogsTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "targetUserId: string, limit?: number, cursor?: string",
    sensitivity: "high",
    auditLabel: "list_admin_user_activity_logs",
    whenToUse: "当管理员要查某位用户最近登录、登出、操作记录时使用。",
    whenNotToUse: "不要用于读取用户资料或 AI 授权数据。",
    argumentHints: ["targetUserId 必填，支持分页"],
    returns: "后台用户活动日志列表。",
  }),
  defineTool(listAdminAIAccessRequestsTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "limit?: number, cursor?: string, status?: string",
    sensitivity: "medium",
    auditLabel: "list_admin_ai_access_requests",
    whenToUse: "当管理员要看 AI 访问申请时使用。",
    whenNotToUse: "不要用于单用户资料或会话查询。",
    argumentHints: ["支持按状态筛选"],
    returns: "AI 访问申请列表。",
  }),
  defineTool(listAdminAIGrantsTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "limit?: number, cursor?: string, status?: string",
    sensitivity: "high",
    auditLabel: "list_admin_ai_grants",
    whenToUse: "当管理员要看 AI 授权记录时使用。",
    whenNotToUse: "不要用于活动日志查询。",
    argumentHints: ["支持按状态筛选"],
    returns: "AI 授权列表。",
  }),
  defineTool(listAdminAIAuditLogsTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "limit?: number, cursor?: string, targetUserId?: string",
    sensitivity: "high",
    auditLabel: "list_admin_ai_audit_logs",
    whenToUse: "当管理员要看 AI 审计轨迹时使用。",
    whenNotToUse: "不要用于普通用户的站内数据查询。",
    argumentHints: ["可按 targetUserId 过滤"],
    returns: "AI 审计日志列表。",
  }),
  defineTool(getAdminOverviewTool, {
    scope: "admin-delegated",
    inputSchemaSummary: "无需输入",
    sensitivity: "medium",
    auditLabel: "read_admin_overview",
    whenToUse: "当管理员想先看后台总览再决定下一步查什么时使用。",
    whenNotToUse: "不要替代具体列表或详情工具。",
    argumentHints: [],
    returns: "后台总览统计。",
  }),
  defineTool(createMarkdownArticleTool, {
    scope: "self",
    inputSchemaSummary: "module: string, title: string, content?: string, summary?: string, tags?: string[], folderId?: string, visibility?: string, date?: string",
    sensitivity: "high",
    auditLabel: "create_markdown_article",
    whenToUse: "当用户要求创建一篇博客、日常、心得或笔记文章时使用。",
    whenNotToUse: "不要用于删除文章、读取他人文章或清空文章内容。不允许删除操作。",
    argumentHints: ["module 必填，可选值：blog/daily/reflections/notes", "title 必填", "visibility 默认 private，可选 private/friends/public", "folderId 可选，传 null 表示根目录"],
    returns: "articleId, slug, title, module, folderId, visibility, date",
  }),
  defineTool(updateMarkdownArticleTool, {
    scope: "self",
    inputSchemaSummary: "module: string, articleId: string, title?: string, content?: string, summary?: string, tags?: string[], folderId?: string, visibility?: string, date?: string",
    sensitivity: "high",
    auditLabel: "update_markdown_article",
    whenToUse: "当用户要求修改自己的某篇文章的标题、正文、摘要、标签、可见性或移动文章到其他文件夹时使用。触发语：'修改那篇文章的标题''帮我改一下博客内容''更新文章正文''把文章改为公开/好友可见'。",
    whenNotToUse: "不要用于删除文章、清空正文内容或修改他人文章。不允许将 content 设为空字符串。",
    argumentHints: ["module 和 articleId 必填", "只修改提供的字段", "content 不能为空字符串", "folderId 传 null 表示移至根目录"],
    returns: "articleId, slug, title, module, folderId, visibility, updatedAt",
  }),
  defineTool(getMarkdownArticleDetailTool, {
    scope: "self",
    inputSchemaSummary: "module: string, articleId?: string, slug?: string",
    sensitivity: "medium",
    auditLabel: "read_markdown_article_detail",
    whenToUse: "当需要读取某篇文章的完整详情（包括正文）以便编辑或参考时使用。",
    whenNotToUse: "不要用于列表浏览或搜索场景，那些用 list_markdown_articles。",
    argumentHints: ["articleId 和 slug 至少提供一个", "module 必填"],
    returns: "文章完整详情，含正文。",
  }),
  defineTool(listMarkdownArticlesTool, {
    scope: "self",
    inputSchemaSummary: "module: string, folderId?: string, keyword?: string, limit?: number",
    sensitivity: "low",
    auditLabel: "list_markdown_articles",
    whenToUse: "当需要列出某个模块下的文章列表、按文件夹筛选或按关键词查找时使用。",
    whenNotToUse: "不要用于读取文章全文，全文用 get_markdown_article_detail。",
    argumentHints: ["module 必填", "limit 默认 10，最大 30", "folderId 为 null 时列出根目录文章"],
    returns: "文章摘要列表，不含正文。",
  }),
  defineTool(createContentFolderTool, {
    scope: "self",
    inputSchemaSummary: "module: string, name: string, description?: string",
    sensitivity: "medium",
    auditLabel: "create_content_folder",
    whenToUse: "当用户要求在 blog/daily/reflections/notes 模块中创建文件夹/分类器时使用。",
    whenNotToUse: "不要用于删除文件夹或跨用户创建文件夹。本系统不支持多级文件夹。",
    argumentHints: ["module 必填", "name 必填", "同名文件夹会自动复用已有文件夹"],
    returns: "folderId, name, module, description",
  }),
  defineTool(listContentFoldersTool, {
    scope: "self",
    inputSchemaSummary: "module: string",
    sensitivity: "low",
    auditLabel: "list_content_folders",
    whenToUse: "当需要列出某个模块下的所有文件夹及其文章数量时使用。",
    whenNotToUse: "不要用于创建或删除文件夹。",
    argumentHints: ["module 必填"],
    returns: "文件夹列表，含 articleCount。",
  }),
  defineTool(moveArticleToFolderTool, {
    scope: "self",
    inputSchemaSummary: "sourceModule: string, articleId: string, targetModule?: string, targetFolderId?: string, confirmedByUser?: boolean",
    sensitivity: "high",
    auditLabel: "move_article_to_folder",
    whenToUse: "当用户要求将文章移动到某个文件夹、移动到根目录或跨模块移动时使用。触发语：'把这篇文章移到……''移动文章到另一个分类''把博客移到笔记里'。",
    whenNotToUse: "不要在没有用户确认的情况下跨模块移动文章。跨模块移动时必须先得到 confirmedByUser=true。",
    argumentHints: [
      "sourceModule 和 articleId 必填",
      "targetModule 默认等于 sourceModule（同模块移动）",
      "targetFolderId 传 null 表示移至根目录",
      "跨模块移动（sourceModule !== targetModule）时 confirmedByUser 必须为 true，否则只返回确认提示",
    ],
    returns: "articleId, title, sourceModule, targetModule, folderId, slug, slugChanged, updatedAt",
  }),
  defineTool(saveUserMemoryTool, {
    scope: "self",
    inputSchemaSummary: "category: string, title: string, content: string, tags?: string[], importance?: string, expiresAt?: string",
    sensitivity: "high",
    auditLabel: "save_user_memory",
    whenToUse: "当用户明确说'记住……''以后都按照……''这是我的偏好……'或表达长期偏好时使用。触发语：'记住我……''以后都按照……''这是我的习惯''记下来，我喜欢……'。",
    whenNotToUse: "不要把所有聊天都保存为记忆。不要保存文章正文、完整对话记录或敏感个人信息（除非用户明确要求）。",
    argumentHints: ["category 必填，可选值：preference/project/decision/workflow/bugfix/content_operation/other", "title 和 content 必填", "importance 默认 medium"],
    returns: "memoryId, title, category, importance, createdAt",
  }),
  defineTool(searchUserMemoryTool, {
    scope: "self",
    inputSchemaSummary: "query: string, category?: string, limit?: number",
    sensitivity: "high",
    auditLabel: "search_user_memory",
    whenToUse: "当用户问'上次怎么说的''之前怎么决定的''按照我的习惯''还记得……吗'时，主动搜索长期记忆。也可搜索对话摘要（MemoryEvent）和工具操作记录（MemoryToolEvent）——当用户问'我们之前聊过什么''你记得我们说过什么吗'时，也可使用此工具。注意：精确的对话统计和消息查询请使用 search_soulwing_conversations。",
    whenNotToUse: "不要在没有明确搜索需求时调用。不要用于闲聊。",
    argumentHints: ["query 必填", "limit 默认 5，最大 20"],
    returns: "匹配的记忆列表，含 type（fact/event/tool_event）、id、title、content、category、createdAt。event 类型为对话摘要，tool_event 类型为工具操作记录。",
  }),
  defineTool(listUserMemoriesTool, {
    scope: "self",
    inputSchemaSummary: "category?: string, limit?: number",
    sensitivity: "medium",
    auditLabel: "list_user_memories",
    whenToUse: "当用户问'你记住了我什么''列出我的记忆''查看我的偏好'时使用。注意：本工具只列出用户主动保存的长期记忆（MemoryFact），不包含对话摘要。如用户询问对话历史，应使用 search_soulwing_conversations。",
    whenNotToUse: "不要用于搜索特定内容，精确搜索用 search_user_memory。不要用于查询对话历史。",
    argumentHints: ["limit 默认 20，最大 50"],
    returns: "记忆摘要列表，含 id/title/category/summary/tags/importance/createdAt，最多返回摘要（content 截断到 120 字）",
  }),
  defineTool(forgetUserMemoryTool, {
    scope: "self",
    inputSchemaSummary: "memoryId: string, confirmedByUser?: boolean",
    sensitivity: "high",
    auditLabel: "forget_user_memory",
    whenToUse: "当用户要求'忘掉这条记忆''删除这条记忆'时使用。只能软删除 MemoryFact。",
    whenNotToUse: "不要删除对话摘要和工具操作记录。不要批量删除。不要在没有用户明确确认的情况下执行删除。",
    argumentHints: ["memoryId 必填", "confirmedByUser 必须为 true 才会执行删除，否则只返回确认提示", "只能软删除，不会真删除数据"],
    returns: "deleted: true, memoryId",
  }),
  // ── AI Conversation History ──────────────────────────────────────────────
  defineTool(searchSoulWingConversationsTool, {
    scope: "self",
    inputSchemaSummary: searchSoulWingConversationsTool.inputSchemaSummary,
    sensitivity: searchSoulWingConversationsTool.sensitivity,
    auditLabel: searchSoulWingConversationsTool.auditLabel,
    whenToUse: searchSoulWingConversationsTool.whenToUse,
    whenNotToUse: searchSoulWingConversationsTool.whenNotToUse,
    argumentHints: searchSoulWingConversationsTool.argumentHints,
    returns: searchSoulWingConversationsTool.returns,
  }),
  defineTool(updateAgentProfileTool, {
    scope: "self",
    inputSchemaSummary: "section: identity|soul|user|rules, operation?: append|replace_section|rewrite, content: string, reason?: string, confirmedByUser?: boolean",
    sensitivity: "high",
    auditLabel: "update_agent_profile",
    whenToUse: "当用户明确表达修改蝶灵的身份(名字/定位)、性格(说话方式/风格)、对用户的认识(长期项目/背景)或行为规则(确认/边界)时使用。触发语：'以后你叫……''以后你回答风格要……''我正在做的长期项目是……''以后必须遵守……'。这不是普通记忆，是蝶灵的长期人格配置。",
    whenNotToUse: "不要因为用户的情绪化吐槽就自动修改人格。不要把整段聊天原文塞进去。不要保存敏感信息。模糊的反馈应先询问而不是自动修改。",
    argumentHints: [
      "section 必填：identity=蝶灵是谁, soul=怎么说话做事, user=认识用户, rules=行为边界",
      "operation 默认 append（追加）；replace_section（替换段）和 rewrite（重写）需要确认",
      "confirmedByUser：高风险修改（RULES/rewrite）必须为 true",
      "reason：建议说明为什么修改",
    ],
    returns: "updated: true, section, operation, preview, version, reason",
  }),
  defineTool(listMyCapabilitiesTool, {
    scope: "self",
    inputSchemaSummary: "categoryId?: string",
    sensitivity: "low",
    auditLabel: "list_capabilities",
    whenToUse: "当用户问【你能做什么】【你有哪些功能】【你会什么】【你有什么工具】时调用，返回全部工具分类和触发短语。",
    whenNotToUse: "不要在明确知道工具名称时调用，直接使用对应工具即可。",
    argumentHints: ["categoryId 可选，传入后只返回该分类"],
    returns: "工具分类列表，含每个分类下的工具名、标题和触发短语。",
  }),
  defineTool(searchMyCapabilitiesTool, {
    scope: "self",
    inputSchemaSummary: "query: string",
    sensitivity: "low",
    auditLabel: "search_capabilities",
    whenToUse: "当用户问【你能不能……】【有没有工具可以……】【你支持……吗】时调用，搜索相关工具能力。",
    whenNotToUse: "不要替代 list_my_capabilities 的整体列举场景。",
    argumentHints: ["query 必填，支持中英文关键词"],
    returns: "匹配的工具列表，含分类、名称、标题、触发短语。",
  }),
  defineTool(webSearchTool, {
    scope: "self",
    inputSchemaSummary: webSearchTool.inputSchemaSummary,
    sensitivity: webSearchTool.sensitivity,
    auditLabel: webSearchTool.auditLabel,
    whenToUse: webSearchTool.whenToUse,
    whenNotToUse: webSearchTool.whenNotToUse,
    argumentHints: webSearchTool.argumentHints,
    returns: webSearchTool.returns,
  }),
  defineTool(webVerifyCurrentInfoTool, {
    scope: "self",
    inputSchemaSummary: webVerifyCurrentInfoTool.inputSchemaSummary,
    sensitivity: webVerifyCurrentInfoTool.sensitivity,
    auditLabel: webVerifyCurrentInfoTool.auditLabel,
    whenToUse: webVerifyCurrentInfoTool.whenToUse,
    whenNotToUse: webVerifyCurrentInfoTool.whenNotToUse,
    argumentHints: webVerifyCurrentInfoTool.argumentHints,
    returns: webVerifyCurrentInfoTool.returns,
  }),
  // ── Phase 4: Persona self-update ────────────────────────────────────────
  defineTool(proposeSaveUserContextTool, {
    scope: "self",
    inputSchemaSummary: proposeSaveUserContextTool.inputSchemaSummary,
    sensitivity: proposeSaveUserContextTool.sensitivity,
    auditLabel: proposeSaveUserContextTool.auditLabel,
    whenToUse: proposeSaveUserContextTool.whenToUse,
    whenNotToUse: proposeSaveUserContextTool.whenNotToUse,
    argumentHints: proposeSaveUserContextTool.argumentHints,
    returns: proposeSaveUserContextTool.returns,
  }),
  // ── Phase 5: Auto-reply ─────────────────────────────────────────────────
  defineTool(getAutoReplySettingsTool, {
    scope: "self",
    inputSchemaSummary: getAutoReplySettingsTool.inputSchemaSummary,
    sensitivity: getAutoReplySettingsTool.sensitivity,
    auditLabel: getAutoReplySettingsTool.auditLabel,
    whenToUse: getAutoReplySettingsTool.whenToUse,
    whenNotToUse: getAutoReplySettingsTool.whenNotToUse,
    argumentHints: getAutoReplySettingsTool.argumentHints,
    returns: getAutoReplySettingsTool.returns,
  }),
  defineTool(updateAutoReplySettingsTool, {
    scope: "self",
    inputSchemaSummary: updateAutoReplySettingsTool.inputSchemaSummary,
    sensitivity: updateAutoReplySettingsTool.sensitivity,
    auditLabel: updateAutoReplySettingsTool.auditLabel,
    whenToUse: updateAutoReplySettingsTool.whenToUse,
    whenNotToUse: updateAutoReplySettingsTool.whenNotToUse,
    argumentHints: updateAutoReplySettingsTool.argumentHints,
    returns: updateAutoReplySettingsTool.returns,
  }),
  // ── Phase 5: Channels ───────────────────────────────────────────────────
  defineTool(listMyChannelsTool, {
    scope: "self",
    inputSchemaSummary: listMyChannelsTool.inputSchemaSummary,
    sensitivity: listMyChannelsTool.sensitivity,
    auditLabel: listMyChannelsTool.auditLabel,
    whenToUse: listMyChannelsTool.whenToUse,
    whenNotToUse: listMyChannelsTool.whenNotToUse,
    argumentHints: listMyChannelsTool.argumentHints,
    returns: listMyChannelsTool.returns,
  }),
  defineTool(getChannelMessagesTool, {
    scope: "self",
    inputSchemaSummary: getChannelMessagesTool.inputSchemaSummary,
    sensitivity: getChannelMessagesTool.sensitivity,
    auditLabel: getChannelMessagesTool.auditLabel,
    whenToUse: getChannelMessagesTool.whenToUse,
    whenNotToUse: getChannelMessagesTool.whenNotToUse,
    argumentHints: getChannelMessagesTool.argumentHints,
    returns: getChannelMessagesTool.returns,
  }),
  defineTool(getSoulWingRoundtableRecordsTool, {
    scope: "self",
    inputSchemaSummary: getSoulWingRoundtableRecordsTool.inputSchemaSummary,
    sensitivity: getSoulWingRoundtableRecordsTool.sensitivity,
    auditLabel: getSoulWingRoundtableRecordsTool.auditLabel,
    whenToUse: getSoulWingRoundtableRecordsTool.whenToUse,
    whenNotToUse: getSoulWingRoundtableRecordsTool.whenNotToUse,
    argumentHints: getSoulWingRoundtableRecordsTool.argumentHints,
    returns: getSoulWingRoundtableRecordsTool.returns,
  }),
  // ── Phase 5: Chat draft ─────────────────────────────────────────────────
  defineTool(sendDraftChatMessageTool, {
    scope: "self",
    inputSchemaSummary: sendDraftChatMessageTool.inputSchemaSummary,
    sensitivity: sendDraftChatMessageTool.sensitivity,
    auditLabel: sendDraftChatMessageTool.auditLabel,
    whenToUse: sendDraftChatMessageTool.whenToUse,
    whenNotToUse: sendDraftChatMessageTool.whenNotToUse,
    argumentHints: sendDraftChatMessageTool.argumentHints,
    returns: sendDraftChatMessageTool.returns,
  }),
  // ── Phase 5: Thread summarization ───────────────────────────────────────
  defineTool(summarizeChatThreadTool, {
    scope: "self",
    inputSchemaSummary: summarizeChatThreadTool.inputSchemaSummary,
    sensitivity: summarizeChatThreadTool.sensitivity,
    auditLabel: summarizeChatThreadTool.auditLabel,
    whenToUse: summarizeChatThreadTool.whenToUse,
    whenNotToUse: summarizeChatThreadTool.whenNotToUse,
    argumentHints: summarizeChatThreadTool.argumentHints,
    returns: summarizeChatThreadTool.returns,
  }),
  // ── Phase 5: Batch memory delete ────────────────────────────────────────
  defineTool(deleteMyMemoryFactBatchTool, {
    scope: "self",
    inputSchemaSummary: deleteMyMemoryFactBatchTool.inputSchemaSummary,
    sensitivity: deleteMyMemoryFactBatchTool.sensitivity,
    auditLabel: deleteMyMemoryFactBatchTool.auditLabel,
    whenToUse: deleteMyMemoryFactBatchTool.whenToUse,
    whenNotToUse: deleteMyMemoryFactBatchTool.whenNotToUse,
    argumentHints: deleteMyMemoryFactBatchTool.argumentHints,
    returns: deleteMyMemoryFactBatchTool.returns,
  }),
  // ── Phase 5: Module visibility ──────────────────────────────────────────
  defineTool(setModuleVisibilityTool, {
    scope: "self",
    inputSchemaSummary: setModuleVisibilityTool.inputSchemaSummary,
    sensitivity: setModuleVisibilityTool.sensitivity,
    auditLabel: setModuleVisibilityTool.auditLabel,
    whenToUse: setModuleVisibilityTool.whenToUse,
    whenNotToUse: setModuleVisibilityTool.whenNotToUse,
    argumentHints: setModuleVisibilityTool.argumentHints,
    returns: setModuleVisibilityTool.returns,
  }),
] as const

export const AI_TOOL_DESCRIPTORS: AIToolDescriptor[] = AI_TOOLS_REGISTRY.map((tool) => ({
  name: tool.name,
  title: tool.title,
  description: tool.description,
  scope: tool.scope,
  inputSchemaSummary: tool.inputSchemaSummary,
  sensitivity: tool.sensitivity,
  auditLabel: tool.auditLabel,
  whenToUse: tool.whenToUse,
  whenNotToUse: tool.whenNotToUse,
  argumentHints: tool.argumentHints,
  returns: tool.returns,
}))

export const AI_TOOL_MAP = new Map(AI_TOOLS_REGISTRY.map((tool) => [tool.name, tool]))
