import { getThemeFieldProfile } from "../../theme-field-profiles"
import type { ResumeThemeAdapter } from "../types"
import { commonBuildRenderInput, commonRender } from "../build-input"

export const paperCnAdapter: ResumeThemeAdapter = {
  templateId: "paper_cn",
  templateName: "Paper 中文",
  pkg: "jsonresume-theme-paper_cn",
  category: "zh",
  sortOrder: 5,
  enabled: true,
  requiresIsolation: "mutex",
  sanitizeLevel: "standard",
  capabilities: {
    localeTitleSupport: "none",
    customOutputLabelSupport: "none",
    sectionOrderSupport: "none",
    appearanceSupport: "wrapperFallback",
    metaThemeSupport: "none",
    pdfSupport: "headlessCompatible",
    supportsChangeLanguage: false,
    builtInLocales: ["zh"],
    supportsDarkMode: false,
    builtInSections: [
      "basics",
      "work",
      "education",
      "projects",
      "skills",
      "languages",
      "awards",
      "publications",
      "interests",
      "volunteer",
      "references",
    ],
    localeMap: {
      "zh-CN": "zh",
      "zh-TW": "zh",
      "zh-HK": "zh",
    },
  },
  defaults: {
    locale: "zh-CN",
    appearance: "system",
    sectionOrder: [
      "basics",
      "work",
      "education",
      "projects",
      "skills",
      "awards",
      "publications",
      "languages",
      "interests",
      "volunteer",
      "references",
    ],
    fieldLabelMap: {
      sections: {
        basics: "基本信息",
        work: "工作经历",
        education: "教育经历",
        projects: "项目经历",
        skills: "技能",
        languages: "语言能力",
        awards: "获奖情况",
        publications: "出版物",
        interests: "兴趣爱好",
        volunteer: "志愿经历",
        references: "推荐信",
      },
    },
    metaTheme: {},
  },
  fieldProfile: getThemeFieldProfile("paper_cn"),
  buildRenderInput: commonBuildRenderInput,
  render: commonRender,
}
