import { getThemeFieldProfile } from "../../theme-field-profiles"
import type { ResumeThemeAdapter } from "../types"
import { commonBuildRenderInput, commonRender } from "../build-input"

export const stackoverflowAdapter: ResumeThemeAdapter = {
  templateId: "stackoverflow",
  templateName: "Stack Overflow",
  pkg: "jsonresume-theme-stackoverflow",
  category: "en",
  sortOrder: 10,
  enabled: true,
  requiresIsolation: "mutex",
  sanitizeLevel: "standard",
  capabilities: {
    localeTitleSupport: "changeLanguage",
    customOutputLabelSupport: "none",
    sectionOrderSupport: "metaSectionOrder",
    appearanceSupport: "nativeDark",
    metaThemeSupport: "full",
    pdfSupport: "native",
    supportsChangeLanguage: true,
    builtInLocales: [
      "en-gb",
      "en",
      "de",
      "fr",
      "es",
      "it",
      "pt",
      "zh",
      "ja",
      "ko",
      "nl",
      "pl",
      "ru",
    ],
    supportsDarkMode: true,
    builtInSections: [
      "basics",
      "work",
      "projects",
      "education",
      "skills",
      "languages",
      "awards",
      "publications",
      "interests",
      "volunteer",
      "references",
    ],
    localeMap: {
      "zh-CN": "zh",
      "zh-TW": "zh",
      "zh-HK": "zh",
      "en-US": "en",
      "en-GB": "en-gb",
    },
  },
  defaults: {
    locale: "en-gb",
    appearance: "system",
    sectionOrder: [
      "work",
      "education",
      "projects",
      "skills",
      "awards",
      "publications",
      "languages",
      "interests",
      "volunteer",
      "references",
    ],
    fieldLabelMap: {},
    metaTheme: {},
  },
  fieldProfile: getThemeFieldProfile("stackoverflow"),
  buildRenderInput: commonBuildRenderInput,
  render: commonRender,
}
